engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true

exclude_patterns:
- ".github/"
- "*.yml"
- ".*.yml"
- "*.md"
- "Gopkg.*"
- "doc.go"
- ".gitignore"
- "LICENSE"
